/**
 * @url /reuse/sc/product/shangou/medicine/recovery/r/detailSp
 */
module.exports = function(req) {
  return {
    "data":{
        "standardProductVo":{
            "medicineTags":null,
            "upcList":[
                "6920698060213"
            ],
            "upcs":null,
            "attrValueList":[
                {
                    "attrName":"注意事项",
                    "valueId":"",
                    "attrId":1200000005,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"性状",
                    "valueId":"",
                    "attrId":1200000006,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"禁忌",
                    "valueId":"",
                    "attrId":1200000010,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"温馨提示",
                    "valueId":"",
                    "attrId":1200000015,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"1.医疗器械请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。2.由于厂家不定期的更换产品包装，如遇新包装上市可能存在更新滞后，请以收到的实货包装为准！3.根据国家相关法律规定，成人用品仅供成年人使用，18岁以下人士请勿购买！请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。"
                },
                {
                    "attrName":"用法用量",
                    "valueId":"",
                    "attrId":1200000017,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"见说明"
                },
                {
                    "attrName":"不良反应",
                    "valueId":"",
                    "attrId":1200000013,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"结构及组成",
                    "valueId":"",
                    "attrId":1200000076,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"产品储存条件",
                    "valueId":"",
                    "attrId":1200000075,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"常温"
                },
                {
                    "attrName":"产品标准",
                    "valueId":"",
                    "attrId":1200000074,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"适用范围",
                    "valueId":"",
                    "attrId":1200000073,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"处方类型",
                    "valueId":"1300000155",
                    "attrId":1200000081,
                    "spSkuId":53092972,
                    "isExt":2,
                    "extension":""
                },
                {
                    "attrName":"有效期",
                    "valueId":"",
                    "attrId":1200000080,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"2022年6月5日"
                },
                {
                    "attrName":"注册人名称",
                    "valueId":"",
                    "attrId":1200000079,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"焦作康业医药材料有限公司"
                },
                {
                    "attrName":"产地类型",
                    "valueId":"1300000003",
                    "attrId":1200000085,
                    "spSkuId":53092972,
                    "isExt":2,
                    "extension":""
                },
                {
                    "attrName":"品牌",
                    "valueId":"0",
                    "attrId":1200000088,
                    "spSkuId":53092972,
                    "isExt":2,
                    "extension":""
                },
                {
                    "attrName":"包装",
                    "valueId":"",
                    "attrId":1200000155,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"10个"
                },
                {
                    "attrName":"产品名称",
                    "valueId":"",
                    "attrId":1200000159,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"一次性使用医用口罩"
                },
                {
                    "attrName":"医疗器械分类",
                    "valueId":"",
                    "attrId":1200000233,
                    "spSkuId":53092972,
                    "isExt":2,
                    "extension":""
                },
                {
                    "attrName":"医疗器械生产许可证/备案编号",
                    "valueId":"",
                    "attrId":1200000314,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"产品技术要求编号",
                    "valueId":"",
                    "attrId":1200000171,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                },
                {
                    "attrName":"注册证编号/备案凭证编号",
                    "valueId":"",
                    "attrId":1200000313,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":"豫械注准20172640565"
                },
                {
                    "attrName":"注册证有效期",
                    "valueId":"",
                    "attrId":1200000315,
                    "spSkuId":53092972,
                    "isExt":1,
                    "extension":""
                }
              ],
              "picDetailList":null,
              "userName":null,
              "category":{
                  "lockStatus":0,
                  "lockTips":null,
                  "level":3,
                  "parentId":0,
                  "categoryId":200000994,
                  "categoryType":2,
                  "categoryName":"口罩",
                  "idPath":",200000966,200000991,200000994,",
                  "categoryNamePath":"医疗器械(药),呼吸用品,口罩",
                  "allowCustomProduct":true,
                  "isLeaf":1
              },
              "wmPoiId":-1,
              "categoryId":null,
              "ctime":0,
              "spec":"10个",
              "medicineTagList":[

              ],
              "spSkuId":53092972,
              "auditStatus":1,
              "picDetails":null,
              "wmPoiName":null,
              "pics":null,
              "picList":[
                  "http://p1.meituan.net/scproduct/ad850d4fd1347c7e3cef3f26df170b65124502.jpg",
                  "http://p0.meituan.net/scproduct/3b418c5f48c72a4c1685e3940ff5eb01162697.jpg"
              ],
              "userId":0,
              "attrValues":null,
              "suggestedPrice":9,
              "name":"一次性使用医用口罩"
          }
      },
      "msg":"",
      "code":0
  }
}
