/**
 * @url reuse/sc/product/retail/r/optionalAndEditableDetail
 */
module.exports = function () {
  return {
    data: {
      editableList: [
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 2,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 0,
          fieldStatus: 3,
          fieldId: 1,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 0
        },
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 2,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 0,
          fieldStatus: 3,
          fieldId: 2,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 0
        },
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 2,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 0,
          fieldStatus: 3,
          fieldId: 3,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 0
        },
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 2,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 0,
          fieldStatus: 3,
          fieldId: 5,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 0
        },
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 2,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 0,
          fieldStatus: 3,
          fieldId: 6,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 0
        }
      ],
      optionalList: [
        {
          setFieldStatus: true,
          setFieldId: true,
          editableRuleType: 1,
          setEditableRuleType: true,
          dimensionId: 106,
          setDimensionId: true,
          dimensionType: 3,
          setDimensionType: true,
          setId: true,
          valid: 1,
          fieldStatus: 2,
          fieldId: 9,
          ctime: 0,
          utime: 0,
          setCtime: true,
          setUtime: true,
          setValid: true,
          muid: 0,
          setMuid: true,
          cuid: 0,
          setCuid: true,
          id: 370894
        }
      ],
      message: ''
    },
    code: 0,
    msg: ''
  };
};
