/**
 * @url /reuse/sc/product/shangou/r/detailProductAndMedicine
 */

// 药品
module.exports = function () {
  return {
    data: {
      spPicContent: '',
      upcImage: null,
      releaseType: 0,
      spPicContentSwitch: 1,
      description: '',
      name: '[浙江泰康]复方鲜竹沥液10ml*6支',
      id: 1190955394,
      labels: null,
      category: {
        lockStatus: 0,
        lockTips: null,
        level: 3,
        parentId: 200000773,
        categoryName: '止咳化痰',
        categoryId: 200000774,
        isLeaf: 1,
        idPath: ',200000763,200000773,200000774,',
        categoryNamePath: '中西药品,呼吸系统,止咳化痰',
        allowCustomProduct: true,
        categoryType: 2
      },
      title: 'Title(title:[浙江泰康]复方鲜竹沥液10ml*6支, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
      wmPoiId: 2868058,
      spId: 0,
      skus: [
        {
          ladderPrice: 0,
          ladderNum: 0,
          skuAttrs: [],
          oriPrice: 0,
          shippingTimeX: '-',
          minOrderCount: 1,
          skuAttrList: null,
          limitStock: 1,
          sequence: 1,
          id: 1323233460,
          shelfNum: '',
          itemNum: '',
          weight: -1,
          price: 54,
          weightUnit: '',
          spuId: null,
          spec: '10ml*6支',
          upcCode: '6932899401054',
          stock: 54,
          unit: '份',
          sourceFoodCode: '54',
          bizValue: null,
          productName: null,
          boxPrice: 0,
          boxNum: 0
        }
      ],
      categoryAttrMap: {
        '1200000003': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '剂型',
          sequence: 14,
          id: 18655907115,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000003,
          valueList: [
            {
              sequence: 0,
              value: '口服液',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '口服液',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000004': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '功能主治',
          sequence: 15,
          id: 18655907113,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000004,
          valueList: [
            {
              sequence: 0,
              value: '清热化痰，止咳。用于痰热咳嗽，痰黄黏稠。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '清热化痰，止咳。用于痰热咳嗽，痰黄黏稠。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000005': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '注意事项',
          sequence: 19,
          id: 18672902656,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000005,
          valueList: [
            {
              sequence: 0,
              value: '1.忌烟、酒及辛辣、生冷、油腻食物。 2.不宜在服药期间同时服用滋补性中药。 3.风寒咳嗽者不适用。 4.支气管扩张、肺脓疡、肺心病、肺结核患者出现咳嗽时应去医院就诊。 5.糖尿病患者及有高血压、心脏病、肝病、肾病等慢性病严重者应在医师指导下服用。 6.儿童、孕妇、哺乳期妇女、年老体弱及脾虚便溏者应在医师指导下服用。 7.服药期间，若患者发热体温超过38.5℃，或出现喘促气急者，或咳嗽加重、痰量明显增多者应去医院就诊。 8.严格按用法用量服用，本品不宜长期服用。 9.服药3天症状无缓解，应去医院就诊。 10.对本品过敏者禁用，过敏体质者慎用。 11.本品性状发生改变时禁止使用。 12.儿童必须在成人监护下使用。 13.请将本品放在儿童不能接触的地方。 14.如正在使用其他药品，使用本品前请咨询医师或药师。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '1.忌烟、酒及辛辣、生冷、油腻食物。 2.不宜在服药期间同时服用滋补性中药。 3.风寒咳嗽者不适用。 4.支气管扩张、肺脓疡、肺心病、肺结核患者出现咳嗽时应去医院就诊。 5.糖尿病患者及有高血压、心脏病、肝病、肾病等慢性病严重者应在医师指导下服用。 6.儿童、孕妇、哺乳期妇女、年老体弱及脾虚便溏者应在医师指导下服用。 7.服药期间，若患者发热体温超过38.5℃，或出现喘促气急者，或咳嗽加重、痰量明显增多者应去医院就诊。 8.严格按用法用量服用，本品不宜长期服用。 9.服药3天症状无缓解，应去医院就诊。 10.对本品过敏者禁用，过敏体质者慎用。 11.本品性状发生改变时禁止使用。 12.儿童必须在成人监护下使用。 13.请将本品放在儿童不能接触的地方。 14.如正在使用其他药品，使用本品前请咨询医师或药师。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000006': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '性状',
          sequence: 13,
          id: 18655907111,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000006,
          valueList: [
            {
              sequence: 0,
              value: '本品为黄棕色至棕色的液体；气香，味甜。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '本品为黄棕色至棕色的液体；气香，味甜。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000010': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '禁忌',
          sequence: 18,
          id: 18672902661,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000010,
          valueList: [
            {
              sequence: 0,
              value: '尚不明确。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '尚不明确。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000013': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '不良反应',
          sequence: 17,
          id: 18672902662,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000013,
          valueList: [
            {
              sequence: 0,
              value: '服后偶有腹泻，停药后自愈。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '服后偶有腹泻，停药后自愈。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000014': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '贮藏',
          sequence: 29,
          id: 18672902660,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000014,
          valueList: [
            {
              sequence: 0,
              value: '密封。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '密封。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000015': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '温馨提示',
          sequence: 34,
          id: 18672902659,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000015,
          valueList: [
            {
              sequence: 0,
              value: '1.OTC药品请按药品说明书或在药师指导下购买和使用。\r\n2.医疗器械请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。\r\n3.保健品不能代替药物。\r\n4.由于厂家不定期的更换产品包装，如遇新包装上市可能存在更新滞后，请以收到的实货包装为准！\r\n5.药品属于特殊商品，除药品质量原因外，药品一经售出，不得退换。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '1.OTC药品请按药品说明书或在药师指导下购买和使用。\r\n2.医疗器械请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。\r\n3.保健品不能代替药物。\r\n4.由于厂家不定期的更换产品包装，如遇新包装上市可能存在更新滞后，请以收到的实货包装为准！\r\n5.药品属于特殊商品，除药品质量原因外，药品一经售出，不得退换。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000016': {
          optionMaxSize: 0,
          textMaxLength: 50,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '商品名',
          sequence: 4,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000016,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000017': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '用法用量',
          sequence: 16,
          id: 18655907118,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000017,
          valueList: [
            {
              sequence: 0,
              value: '口服。一次20毫升（2支），一日2～3次。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '口服。一次20毫升（2支），一日2～3次。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000020': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '药物相互作用',
          sequence: 24,
          id: 18655907119,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000020,
          valueList: [
            {
              sequence: 0,
              value: '如与其他药物同时使用可能会发生药物相互作用，详情请咨询医师或药师。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '如与其他药物同时使用可能会发生药物相互作用，详情请咨询医师或药师。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000025': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '生产单位',
          sequence: 11,
          id: 18655907121,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000025,
          valueList: [
            {
              sequence: 0,
              value: '浙江泰康药业集团有限公司',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '浙江泰康药业集团有限公司',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000030': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '执行标准',
          sequence: 32,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000030,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000040': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '药代动力学',
          sequence: 28,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000040,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000052': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '老年人用药',
          sequence: 22,
          id: 28082496239,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000052,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000059': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '儿童用药',
          sequence: 21,
          id: 28082888388,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000059,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000061': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '药物过量',
          sequence: 25,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000061,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000080': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '有效期',
          sequence: 31,
          id: 18655907110,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000080,
          valueList: [
            {
              sequence: 0,
              value: '24个月',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '24个月',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000081': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '处方类型',
          sequence: 3,
          id: 18655907108,
          level: 0,
          inputType: 1,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000081,
          valueList: [
            {
              sequence: 0,
              value: 'OTC',
              text: '1',
              isLeaf: 0,
              selected: 1,
              valueId: 1300000152,
              valuePath: '1',
              valueIdPath: '1300000152'
            },
            {
              sequence: 0,
              value: '非药品',
              text: '0',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000155,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '处方药',
              text: '2',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000153,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '通用品',
              text: '3',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000154,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 1
        },
        '1200000082': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '药品通用名称',
          sequence: 2,
          id: 18655907109,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000082,
          valueList: [
            {
              sequence: 0,
              value: '复方鲜竹沥液',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '复方鲜竹沥液',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000085': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '产地类型',
          sequence: 8,
          id: 18672902655,
          level: 0,
          inputType: 1,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000085,
          valueList: [
            {
              sequence: 0,
              value: '国产',
              text: '1',
              isLeaf: 0,
              selected: 1,
              valueId: 1300000003,
              valuePath: '1',
              valueIdPath: '1300000003'
            },
            {
              sequence: 0,
              value: '进口',
              text: '2',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000004,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000086': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '批准文号',
          sequence: 6,
          id: 18655907107,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000086,
          valueList: [
            {
              sequence: 0,
              value: '国药准字Z20053633',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '国药准字Z20053633',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 1
        },
        '1200000088': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '品牌',
          sequence: 5,
          id: 18672902653,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000088,
          valueList: [
            {
              sequence: 0,
              value: '浙江泰康',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 100003537,
              valuePath: '浙江泰康',
              valueIdPath: '100003537'
            },
            {
              sequence: 0,
              value: '浙江泰康',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '浙江泰康',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 1
        },
        '1200000117': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '是否外用',
          sequence: 10,
          id: 0,
          level: 0,
          inputType: 1,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000117,
          valueList: [
            {
              sequence: 0,
              value: '是',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000096,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '否',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000095,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000150': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '临床试验',
          sequence: 26,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000150,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000151': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '警告/警示语',
          sequence: 33,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000151,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000153': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '孕妇及哺乳期妇女',
          sequence: 20,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000153,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000154': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '药理毒理',
          sequence: 27,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000154,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        },
        '1200000155': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '包装',
          sequence: 30,
          id: 18672902666,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 200000774,
          isLeaf: 0,
          spuId: 1190955394,
          attrId: 1200000155,
          valueList: [
            {
              sequence: 0,
              value: '玻璃瓶。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '玻璃瓶。',
              valueIdPath: '0'
            }
          ],
          templateId: 101,
          isRequired: 1,
          attrType: 3
        },
        '1200000243': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '是否为抗生素',
          sequence: 9,
          id: 0,
          level: 0,
          inputType: 1,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000243,
          valueList: [
            {
              sequence: 0,
              value: '是',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000096,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '否',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000095,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 101,
          isRequired: 2,
          attrType: 1
        },
        '1200000311': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '成份',
          sequence: 12,
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000311,
          valueList: null,
          templateId: 101,
          isRequired: 2,
          attrType: 3
        }
      },
      spuSaleAttrMap: null,
      tagList: [
        {
          categoryCode: '',
          outerFtagId: -1,
          description: '',
          timeZone: '',
          sequence: 3,
          parentName: 'a',
          level: 2,
          tagName: 'a2',
          extend: '',
          parentId: 172009786,
          topFlag: 0,
          isLeaf: 1,
          tagId: 172010677,
          appTagCode: '',
          tagType: 0,
          actPolicyId: 0,
          nodePath: '',
          buzType: 9
        }
      ],
      limitSale: '{"limitSale":false,"begin":"","end":"","type":1,"frequency":1,"count":0}',
      sellStatus: 0,
      shippingTimeX: '-',
      picture: '',
      attrList: [],
      isSp: 0,
      poorImages: null,
      picContent: '',
      auditStatus: 0,
      wmProductVideo: null,
      suggestedPrice: 0,
      riseMax: 0,
      dropMax: 0,
      minOrderCount: 1
    },
    code: 0,
    msg: '成功'
  }
  // return {
  //   data: {
  //     spPicContent: '',
  //     upcImage: null,
  //     releaseType: 0,
  //     spPicContentSwitch: 1,
  //     description: '',
  //     name: '雪宜 抗病毒口服液 10支',
  //     id: 12531606,
  //     labels: null,
  //     category: {
  //       lockStatus: 0,
  //       lockTips: null,
  //       level: 3,
  //       parentId: 900002597,
  //       categoryId: 900002598,
  //       categoryType: 2,
  //       categoryName: 'SZH三级目录',
  //       isLeaf: 1,
  //       allowCustomProduct: true,
  //       idPath: ',900002596,900002597,900002598,',
  //       categoryNamePath: 'SZH一级目录,SZH二级目录,SZH三级目录'
  //     },
  //     title: 'Title(title:雪宜 抗病毒口服液 10支, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
  //     wmPoiId: 612222,
  //     spId: 0,
  //     skus: [
  //       {
  //         ladderPrice: 0,
  //         ladderNum: 0,
  //         skuAttrs: [],
  //         minOrderCount: 1,
  //         oriPrice: 8,
  //         shippingTimeX: '-',
  //         skuAttrList: null,
  //         shelfNum: '',
  //         itemNum: '',
  //         id: 133019924,
  //         sequence: 0,
  //         weight: 0,
  //         price: 11,
  //         weightUnit: '克(g)',
  //         spuId: null,
  //         spec: '每支装10毫升，每盒装10支。',
  //         stock: 11,
  //         sourceFoodCode: '',
  //         upcCode: '8888111',
  //         unit: '份',
  //         bizValue: null,
  //         productName: null,
  //         boxPrice: 0,
  //         boxNum: 0,
  //         limitStock: 1
  //       }
  //     ],
  //     categoryAttrMap: {
  //       '100003010': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: ' 包装规格',
  //         id: 0,
  //         sequence: 8,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003010,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 2
  //       },
  //       '100003011': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '药品通用名称',
  //         id: 0,
  //         sequence: 9,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003011,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 1
  //       },
  //       '100003012': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '生产单位',
  //         id: 0,
  //         sequence: 10,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003012,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 1
  //       },
  //       '100003013': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: ' 贮藏',
  //         id: 0,
  //         sequence: 11,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003013,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 1
  //       },
  //       '100003081': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '颜色',
  //         id: 0,
  //         sequence: 1,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002596,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003081,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 2
  //       },
  //       '100003090': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '大小',
  //         id: 0,
  //         sequence: 12,
  //         level: 0,
  //         inputType: 1,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003090,
  //         attrType: 3,
  //         templateId: 0,
  //         isRequired: 2
  //       },
  //       '1200000017': {
  //         optionMaxSize: 0,
  //         textMaxLength: 300,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '用法用量',
  //         id: 0,
  //         sequence: 6,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 1200000017,
  //         attrType: 3,
  //         templateId: 2062,
  //         isRequired: 1
  //       },
  //       '1200000080': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '有效期',
  //         id: 0,
  //         sequence: 5,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 1200000080,
  //         attrType: 3,
  //         templateId: 2062,
  //         isRequired: 1
  //       },
  //       '1200000085': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '1',
  //         application: '1,2',
  //         attrName: '产地类型',
  //         id: 0,
  //         sequence: 7,
  //         level: 0,
  //         inputType: 1,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: [
  //           {
  //             value: '国产',
  //             sequence: 0,
  //             text: '1',
  //             isLeaf: 0,
  //             valueId: 1593,
  //             valueIdPath: null,
  //             valuePath: null,
  //             selected: 0
  //           },
  //           {
  //             value: '进口',
  //             sequence: 0,
  //             text: '2',
  //             isLeaf: 0,
  //             valueId: 1594,
  //             valueIdPath: null,
  //             valuePath: null,
  //             selected: 0
  //           }
  //         ],
  //         attrId: 1200000085,
  //         attrType: 3,
  //         templateId: 2062,
  //         isRequired: 1
  //       },
  //       '1200000086': {
  //         optionMaxSize: 0,
  //         textMaxLength: 222,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '批准文号',
  //         id: 0,
  //         sequence: 4,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 1200000086,
  //         attrType: 1,
  //         templateId: 2062,
  //         isRequired: 1
  //       },
  //       '1200000088': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '品牌',
  //         id: 0,
  //         sequence: 3,
  //         level: 0,
  //         inputType: 3,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 1200000088,
  //         attrType: 1,
  //         templateId: 2062,
  //         isRequired: 1
  //       }
  //     },
  //     spuSaleAttrMap: {
  //       '100003210': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2,3',
  //         attrName: '销售属性1',
  //         id: 0,
  //         sequence: 2,
  //         level: 0,
  //         inputType: 2,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003210,
  //         attrType: 2,
  //         templateId: 0,
  //         isRequired: 1
  //       },
  //       '100003211': {
  //         optionMaxSize: 0,
  //         textMaxLength: 30,
  //         characterType: '1,2,3,4',
  //         supportFilter: 2,
  //         supportExtend: '',
  //         application: '1,2',
  //         attrName: '销售属性2',
  //         id: 0,
  //         sequence: 1,
  //         level: 0,
  //         inputType: 2,
  //         categoryId: 900002598,
  //         wmPoiId: 0,
  //         isLeaf: 0,
  //         spuId: 0,
  //         valueList: null,
  //         attrId: 100003211,
  //         attrType: 2,
  //         templateId: 0,
  //         isRequired: 1
  //       }
  //     },
  //     tagList: [
  //       {
  //         categoryCode: '',
  //         outerFtagId: -1,
  //         timeZone: '',
  //         description: '',
  //         sequence: 0,
  //         level: 1,
  //         tagName: '未分类',
  //         extend: '',
  //         parentName: null,
  //         parentId: 0,
  //         topFlag: 0,
  //         isLeaf: 1,
  //         tagId: 7512457,
  //         appTagCode: '',
  //         tagType: 0,
  //         actPolicyId: 0,
  //         nodePath: '',
  //         buzType: 9
  //       }
  //     ],
  //     limitSale: '',
  //     auditStatus: 0,
  //     sellStatus: 0,
  //     attrList: [],
  //     isSp: 0,
  //     minOrderCount: 1,
  //     suggestedPrice: 0,
  //     picture: 'http://p0.meituan.net/xianfu/5372dd1aff80409ce635b22dc77200d323036.jpg,http://p0.meituan.net/xianfu/baabbb83a0b724900be5ad783666fbad16094.jpg,,,',
  //     shippingTimeX: '-',
  //     poorImages: [
  //       1,
  //       2
  //     ],
  //     picContent: '',
  //     wmProductVideo: null,
  //     riseMax: 0,
  //     dropMax: 0
  //   },
  //   code: 0,
  //   msg: '成功'
  // }
}
// 商品
// module.exports = function () {
//   return {
//     code: 0,
//     data: {
//       name: '[天龙]维胺酯维E乳膏',
//       id: 111111,
//       auditStatus: 0,
//       limitSale: JSON.stringify({
//         limitSale: false,
//         begin: '20200301',
//         end: '20200401',
//         type: 2,
//         count: 100
//       }),
//       tagList: [
//         {
//           tagName: '403二级分类',
//           tagId: 96851308,
//           valid: 1,
//           isLeaf: 1,
//           setId: true,
//           setName: true,
//           setSequence: true,
//           setCtime: true,
//           setUtime: true,
//           setValid: true,
//           setDescription: true,
//           tagType: 0,
//           parentId: 7340747,
//           setWmPoiId: true,
//           setPoiId: true,
//           setIsLeaf: true,
//           setParentName: true,
//           setBuzType: true,
//           appTagCode: '',
//           setAppTagCode: true,
//           setTopFlag: true,
//           setTagType: true,
//           setTimeZone: true,
//           setActPolicyId: true,
//           setCategoryCode: true,
//           setNodePath: true,
//           outerFtagId: -1,
//           setOuterFtagId: true,
//           setExtend: true,
//           topFlag: 0,
//           description: '',
//           parentName: '403一级分类',
//           wmPoiId: 5108726,
//           setLevel: true,
//           actPolicyId: 0,
//           nodePath: '',
//           buzType: 0,
//           setParentId: true,
//           categoryCode: '',
//           extend: '{"sortType":2,"topCount":0}',
//           utime: 1554259012,
//           ctime: 1509005478,
//           poiId: 0,
//           timeZone: '',
//           level: 2,
//           sequence: 6
//         }
//       ],
//       categoryAttrMap: {
//         '300000028': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '大乳品',
//           attrId: 300000028,
//           attrType: 1,
//           supportExtend: true,
//           'valueList|3': [
//             {
//               value: '@name',
//               'valueId|+1': [400002677, 400002678, 400002679],
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 1,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 2
//         },
//         '1200000094': {
//           id: 1200000088,
//           attrName: '产地',
//           attrId: 1200000094,
//           attrType: 1,
//           valueList: [{
//             value: 'test',
//             valueId: '',
//             valueIdPath: '',
//             valuePath: 'test',
//             selected: 1,
//             text: '',
//             sequence: 0
//           }]
//         },
//         '1200000088': {
//           id: 1200000088,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '品牌',
//           attrId: 1200000088,
//           attrType: 1,
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 0,
//           inputType: 3,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 1,
//           valueList: [{
//             value: '大苹果',
//             valueId: 123,
//             valueIdPath: '123',
//             valuePath: '大苹果',
//             selected: 1,
//             text: '',
//             sequence: 0
//           }]
//         },
//         '300005192': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: 'adfa',
//           attrId: 300005192,
//           optionMaxSize: 5,
//           attrType: 1,
//           supportExtend: true,
//           valueList: [
//             {
//               value: '1-6789',
//               valueId: 400003137,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '1-1234dsfdsfadsf5',
//               valueId: 400003136,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-xcvcxvx',
//               valueId: null,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '1-66745645',
//               valueId: 423423423423,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-666',
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-76765679',
//               valueId: null,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 4
//         },
//         '300005193': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '文本',
//           attrId: 300005193,
//           attrType: 1,
//           valueList: [
//             {
//               value: 'hhh',
//               selected: 1
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           textMaxLength: 4096,
//           characterType: '2',
//           inputType: 3,
//           wmPoiId: '123',
//           level: 0,
//           sequence: 5
//         }
//       },
//       attrList: [],
//       picture: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg,,,,',
//       upcImage: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
//       picContent: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
//       spPicContentSwitch: 1,
//       spPicContent: "http://p0.meituan.net/scproduct/9187625ab832e8cfdb74755826ddae09280843.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/d8405b2203ada027b1ff0ad2f78a4a6a370718.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/c49ce6f332fea63cd92fef0889bad3e888259.jpg?w=1125&h=1125,http://p0.meituan.net/scproduct/9969aa40d7e6f15828dfed0b39a60bf2226215.jpg?w=2048&h=2048",
//       poorImages: [1],
//       'wmProductVideo|1': [
//         {
//           'id': 1111,
//           'length': 76,
//           title: '@name',
//           main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
//           main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
//           'size': 343,
//           url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
//           url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
//           'status|1': [1],
//           ctime: 1559216594894,
//           utime: 1559216594894,
//           'relSpuList|0-3': [
//             {
//               'id|+1': 1000,
//               name: '@name',
//               picture: 'https://avatars1.githubusercontent.com/u/9376569?s=460&v=4',
//               upcCode: '123',
//               wmProductSkus: [
//                 {
//                   upcCode: '123',
//                   price: 5,
//                   stock: 10
//                 }
//               ]
//             }
//           ],
//         },
//       ],
//       suggestedPrice: 0,
//       riseMax: 0,
//       dropMax: 0,
//       offShelfType: 0,
//       releaseType: 0,
//       upcValidFlag: 0,
//       riskMano: null,
//       labels: [{subAttr: "0", id: 1, groupId: 1, groupName: "招牌"}],
//       spuSaleAttrMap: {
//         '300000029': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '颜色1',
//           attrId: 300000029,
//           valueList: [
//             {
//               value: '红色',
//               valueId: 0,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: null,
//               sequence: 0,
//               isCustomized: true,
//             },
//             {
//               value: '白色',
//               valueId: 1,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '黄色',
//               valueId: 2,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '绿色',
//               valueId: 3,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 0,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 2,
//           attrType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 0
//         },
//         '300000030': {
//           id: 1,
//           isLeaf: 0,
//           spuId: 1,
//           attrName: '颜色2',
//           attrId: 300000030,
//           valueList: [
//             {
//               value: '红色',
//               valueId: 0,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: null,
//               sequence: 0,
//               isCustomized: true,
//             },
//             {
//               value: '白色',
//               valueId: 1,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '黄色',
//               valueId: 2,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '绿色',
//               valueId: 3,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 1,
//           templateId: 1,
//           isRequired: 1,
//           inputType: 2,
//           attrType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 1
//         }
//       },
//       forceRelFlag: 0,
//       sellStatus: 0,
//       minOrderCount: 1,
//       shippingTimeX: '[[],["11:21-11:24"],["11:21-11:24"],[],["11:21-11:24"],[],[]]',
//       skus: [
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }],
//           minOrderCount: 1,
//           id: 130332025,
//           stock: 10,
//           price: 0,
//           upcCode: '33334444111',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 0,
//           ladderNum: 0,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332026,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '红色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332027,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '白色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332028,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         }
//       ],
//       title: 'Title(title:商品11, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
//       description: '',
//       items: null,
//       category: {
//         idPath: ',200000763,200000768,200000769,',
//         categoryNamePath: '中西药品,感冒用药,清热解毒',
//         isLeaf: 1,
//         categoryId: 200000769,
//         parentId: 200000087,
//         categoryName: '袋装冰激凌',
//         level: 3
//       },
//       wmPoiId: 5108726,
//       isSp: 1,
//       spId: 1
//     },
//     msg: '成功'
//   };
// };
