/**
 * @url /reuse/sc/product/shangou/r/detailProduct
 */
module.exports = function () {
  return {
    code: 0,
    data: {
      saleType: 2,
      deliveryTime: 1620385000000,
      name: '商品11',
      id: 10294879,
      auditStatus: 0,
      limitSale: JSON.stringify({
        limitSale: false,
        begin: '20200301',
        end: '20200401',
        type: 2,
        count: 100
      }),
      tagList: [
        {
          tagName: '403二级分类',
          tagId: 96851308,
          valid: 1,
          isLeaf: 1,
          setId: true,
          setName: true,
          setSequence: true,
          setCtime: true,
          setUtime: true,
          setValid: true,
          setDescription: true,
          tagType: 0,
          parentId: 7340747,
          setWmPoiId: true,
          setPoiId: true,
          setIsLeaf: true,
          setParentName: true,
          setBuzType: true,
          appTagCode: '',
          setAppTagCode: true,
          setTopFlag: true,
          setTagType: true,
          setTimeZone: true,
          setActPolicyId: true,
          setCategoryCode: true,
          setNodePath: true,
          outerFtagId: -1,
          setOuterFtagId: true,
          setExtend: true,
          topFlag: 0,
          description: '',
          parentName: '403一级分类',
          wmPoiId: 5108726,
          setLevel: true,
          actPolicyId: 0,
          nodePath: '',
          buzType: 0,
          setParentId: true,
          categoryCode: '',
          extend: '{"sortType":2,"topCount":0}',
          utime: 1554259012,
          ctime: 1509005478,
          poiId: 0,
          timeZone: '',
          level: 2,
          sequence: 6
        }
      ],
      categoryAttrMap: {
        '300000028': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '大乳品',
          attrId: 300000028,
          attrType: 1,
          supportExtend: true,
          'valueList|3': [
            {
              value: '@name',
              'valueId|+1': [400002677, 400002678, 400002679],
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          inputType: 1,
          wmPoiId: 0,
          level: 0,
          sequence: 2
        },
        '1200000094': {
          id: 1200000088,
          attrName: '产地',
          attrId: 1200000094,
          attrType: 1,
          valueList: [{
            value: 'test',
            valueId: '',
            valueIdPath: '',
            valuePath: 'test',
            selected: 1,
            text: '',
            sequence: 0
          }]
        },
        '1200000088': {
          id: 1200000088,
          isLeaf: 0,
          spuId: 0,
          attrName: '品牌',
          attrId: 1200000088,
          attrType: 1,
          categoryId: 200000062,
          templateId: 0,
          isRequired: 0,
          inputType: 3,
          wmPoiId: 0,
          level: 0,
          sequence: 1,
          valueList: [{
            value: '大苹果',
            valueId: 123,
            valueIdPath: '123',
            valuePath: '大苹果',
            selected: 1,
            text: '',
            sequence: 0
          }]
        },
        '300005192': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: 'adfa',
          attrId: 300005192,
          optionMaxSize: 5,
          attrType: 1,
          supportExtend: true,
          valueList: [
            {
              value: '1-6789',
              valueId: 400003137,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '1-1234dsfdsfadsf5',
              valueId: 400003136,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '0-xcvcxvx',
              valueId: null,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '1-66745645',
              valueId: 423423423423,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '0-666',
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '0-76765679',
              valueId: null,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          inputType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 4
        },
        '300005193': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '文本',
          attrId: 300005193,
          attrType: 1,
          valueList: [
            {
              value: 'hhh',
              selected: 1
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          textMaxLength: 4096,
          characterType: '2',
          inputType: 3,
          wmPoiId: '123',
          level: 0,
          sequence: 5
        }
      },
      attrList: [],
      picture: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg,,,,',
      upcImage: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
      picContent: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
      spPicContentSwitch: 1,
      spPicContent: "http://p0.meituan.net/scproduct/9187625ab832e8cfdb74755826ddae09280843.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/d8405b2203ada027b1ff0ad2f78a4a6a370718.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/c49ce6f332fea63cd92fef0889bad3e888259.jpg?w=1125&h=1125,http://p0.meituan.net/scproduct/9969aa40d7e6f15828dfed0b39a60bf2226215.jpg?w=2048&h=2048",
      poorImages: [1],
      'wmProductVideo|1': [
        {
          'id': 1111,
          'length': 76,
          title: '@name',
          main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
          main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
          'size': 343,
          url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
          url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
          'status|1': [1],
          ctime: 1559216594894,
          utime: 1559216594894,
          'relSpuList|0-3': [
            {
              'id|+1': 1000,
              name: '@name',
              picture: 'https://avatars1.githubusercontent.com/u/9376569?s=460&v=4',
              upcCode: '123',
              wmProductSkus: [
                {
                  upcCode: '123',
                  price: 5,
                  stock: 10
                }
              ]
            }
          ],
        },
      ],
      suggestedPrice: 0,
      riseMax: 0,
      dropMax: 0,
      offShelfType: 0,
      releaseType: 0,
      upcValidFlag: 0,
      riskMano: null,
      labels: [{subAttr: "0", id: 1, groupId: 1, groupName: "招牌"}],
      spuSaleAttrMap: {
        '300000029': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '颜色1',
          attrId: 300000029,
          valueList: [
            {
              value: '红色',
              valueId: 0,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: null,
              sequence: 0,
              isCustomized: true,
            },
            {
              value: '白色',
              valueId: 1,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '黄色',
              valueId: 2,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '绿色',
              valueId: 3,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 0,
          templateId: 0,
          isRequired: 1,
          inputType: 2,
          attrType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 0
        },
        '300000030': {
          id: 1,
          isLeaf: 0,
          spuId: 1,
          attrName: '颜色2',
          attrId: 300000030,
          valueList: [
            {
              value: '红色',
              valueId: 0,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: null,
              sequence: 0,
              isCustomized: true,
            },
            {
              value: '白色',
              valueId: 1,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '黄色',
              valueId: 2,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '绿色',
              valueId: 3,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 1,
          templateId: 1,
          isRequired: 1,
          inputType: 2,
          attrType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 1
        }
      },
      forceRelFlag: 0,
      sellStatus: 0,
      minOrderCount: 1,
      shippingTimeX: '[[],["11:21-11:24"],["11:21-11:24"],[],["11:21-11:24"],[],[]]',
      skus: [
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }],
          minOrderCount: 1,
          id: 130332025,
          stock: 0,
          price: 0,
          upcCode: '33334444111',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 0,
          ladderNum: 0,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        },
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332026,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        },
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '红色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332027,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        },
        {
          skuAttrs: [{
            value: '白色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332028,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        }
      ],
      title: 'Title(title:商品11, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
      description: '',
      items: null,
      category: {
        idPath: ',200000062,200000087,200000088,',
        categoryNamePath: '制品,冰品,袋装冰激凌',
        isLeaf: 1,
        categoryId: 200000088,
        parentId: 200000087,
        categoryName: '袋装冰激凌',
        level: 3
      },
      wmPoiId: 5108726,
      isSp: 1,
      spId: 0,
      missingRequiredInfo: true
    },
    msg: '成功'
  };
};
