/**
 * @url /reuse/sc/product/shangou/r/detailProductAndMedicine
 */

// 药品
module.exports = function () {
  return {
    data: {
      spPicContent: '',
      upcImage: null,
      releaseType: 0,
      spPicContentSwitch: 1,
      description: '',
      name: '雪宜 抗病毒口服液 10支',
      id: 12531606,
      labels: null,
      category: {
        lockStatus: 0,
        lockTips: null,
        level: 3,
        parentId: 900002597,
        categoryId: 900002598,
        categoryType: 2,
        categoryName: 'SZH三级目录',
        isLeaf: 1,
        allowCustomProduct: true,
        idPath: ',900002596,900002597,900002598,',
        categoryNamePath: 'SZH一级目录,SZH二级目录,SZH三级目录'
      },
      title: 'Title(title:雪宜 抗病毒口服液 10支, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
      wmPoiId: 612222,
      spId: 0,
      skus: [
        {
          ladderPrice: 0,
          ladderNum: 0,
          skuAttrs: [],
          minOrderCount: 1,
          oriPrice: 8,
          shippingTimeX: '-',
          skuAttrList: null,
          shelfNum: '',
          itemNum: '',
          id: 133019924,
          sequence: 0,
          weight: 0,
          price: 11,
          weightUnit: '克(g)',
          spuId: null,
          spec: '每支装10毫升，每盒装10支。',
          stock: 11,
          sourceFoodCode: '',
          upcCode: '8888111',
          unit: '份',
          bizValue: null,
          productName: null,
          boxPrice: 0,
          boxNum: 0,
          limitStock: 1
        }
      ],
      categoryAttrMap: {
        '100003010': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: ' 包装规格',
          id: 0,
          sequence: 8,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003010,
          attrType: 3,
          templateId: 0,
          isRequired: 2
        },
        '100003011': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '药品通用名称',
          id: 0,
          sequence: 9,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003011,
          attrType: 3,
          templateId: 0,
          isRequired: 1
        },
        '100003012': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '生产单位',
          id: 0,
          sequence: 10,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003012,
          attrType: 3,
          templateId: 0,
          isRequired: 1
        },
        '100003013': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: ' 贮藏',
          id: 0,
          sequence: 11,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003013,
          attrType: 3,
          templateId: 0,
          isRequired: 1
        },
        '100003081': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '颜色',
          id: 0,
          sequence: 1,
          level: 0,
          inputType: 3,
          categoryId: 900002596,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003081,
          attrType: 3,
          templateId: 0,
          isRequired: 2
        },
        '100003090': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '大小',
          id: 0,
          sequence: 12,
          level: 0,
          inputType: 1,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003090,
          attrType: 3,
          templateId: 0,
          isRequired: 2
        },
        '1200000017': {
          optionMaxSize: 0,
          textMaxLength: 300,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '用法用量',
          id: 0,
          sequence: 6,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 1200000017,
          attrType: 3,
          templateId: 2062,
          isRequired: 1
        },
        '1200000080': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '有效期',
          id: 0,
          sequence: 5,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 1200000080,
          attrType: 3,
          templateId: 2062,
          isRequired: 1
        },
        '1200000085': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          attrName: '产地类型',
          id: 0,
          sequence: 7,
          level: 0,
          inputType: 1,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: [
            {
              value: '国产',
              sequence: 0,
              text: '1',
              isLeaf: 0,
              valueId: 1593,
              valueIdPath: null,
              valuePath: null,
              selected: 0
            },
            {
              value: '进口',
              sequence: 0,
              text: '2',
              isLeaf: 0,
              valueId: 1594,
              valueIdPath: null,
              valuePath: null,
              selected: 0
            }
          ],
          attrId: 1200000085,
          attrType: 3,
          templateId: 2062,
          isRequired: 1
        },
        '1200000086': {
          optionMaxSize: 0,
          textMaxLength: 222,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '批准文号',
          id: 0,
          sequence: 4,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 1200000086,
          attrType: 1,
          templateId: 2062,
          isRequired: 1
        },
        '1200000088': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '品牌',
          id: 0,
          sequence: 3,
          level: 0,
          inputType: 3,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 1200000088,
          attrType: 1,
          templateId: 2062,
          isRequired: 1
        }
      },
      spuSaleAttrMap: {
        '100003210': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2,3',
          attrName: '销售属性1',
          id: 0,
          sequence: 2,
          level: 0,
          inputType: 2,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003210,
          attrType: 2,
          templateId: 0,
          isRequired: 1
        },
        '100003211': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          attrName: '销售属性2',
          id: 0,
          sequence: 1,
          level: 0,
          inputType: 2,
          categoryId: 900002598,
          wmPoiId: 0,
          isLeaf: 0,
          spuId: 0,
          valueList: null,
          attrId: 100003211,
          attrType: 2,
          templateId: 0,
          isRequired: 1
        }
      },
      tagList: [
        {
          categoryCode: '',
          outerFtagId: -1,
          timeZone: '',
          description: '',
          sequence: 0,
          level: 1,
          tagName: '未分类',
          extend: '',
          parentName: null,
          parentId: 0,
          topFlag: 0,
          isLeaf: 1,
          tagId: 7512457,
          appTagCode: '',
          tagType: 0,
          actPolicyId: 0,
          nodePath: '',
          buzType: 9
        }
      ],
      limitSale: '',
      auditStatus: 0,
      sellStatus: 0,
      attrList: [],
      isSp: 0,
      minOrderCount: 1,
      suggestedPrice: 0,
      picture: 'http://p0.meituan.net/xianfu/5372dd1aff80409ce635b22dc77200d323036.jpg,http://p0.meituan.net/xianfu/baabbb83a0b724900be5ad783666fbad16094.jpg,,,',
      shippingTimeX: '-',
      poorImages: [
        1,
        2
      ],
      picContent: '',
      wmProductVideo: null,
      riseMax: 0,
      dropMax: 0
    },
    code: 0,
    msg: '成功'
  }
}
// 商品
// module.exports = function () {
//   return {
//     code: 0,
//     data: {
//       name: '[天龙]维胺酯维E乳膏',
//       id: 111111,
//       auditStatus: 0,
//       limitSale: JSON.stringify({
//         limitSale: false,
//         begin: '20200301',
//         end: '20200401',
//         type: 2,
//         count: 100
//       }),
//       tagList: [
//         {
//           tagName: '403二级分类',
//           tagId: 96851308,
//           valid: 1,
//           isLeaf: 1,
//           setId: true,
//           setName: true,
//           setSequence: true,
//           setCtime: true,
//           setUtime: true,
//           setValid: true,
//           setDescription: true,
//           tagType: 0,
//           parentId: 7340747,
//           setWmPoiId: true,
//           setPoiId: true,
//           setIsLeaf: true,
//           setParentName: true,
//           setBuzType: true,
//           appTagCode: '',
//           setAppTagCode: true,
//           setTopFlag: true,
//           setTagType: true,
//           setTimeZone: true,
//           setActPolicyId: true,
//           setCategoryCode: true,
//           setNodePath: true,
//           outerFtagId: -1,
//           setOuterFtagId: true,
//           setExtend: true,
//           topFlag: 0,
//           description: '',
//           parentName: '403一级分类',
//           wmPoiId: 5108726,
//           setLevel: true,
//           actPolicyId: 0,
//           nodePath: '',
//           buzType: 0,
//           setParentId: true,
//           categoryCode: '',
//           extend: '{"sortType":2,"topCount":0}',
//           utime: 1554259012,
//           ctime: 1509005478,
//           poiId: 0,
//           timeZone: '',
//           level: 2,
//           sequence: 6
//         }
//       ],
//       categoryAttrMap: {
//         '300000028': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '大乳品',
//           attrId: 300000028,
//           attrType: 1,
//           supportExtend: true,
//           'valueList|3': [
//             {
//               value: '@name',
//               'valueId|+1': [400002677, 400002678, 400002679],
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 1,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 2
//         },
//         '1200000094': {
//           id: 1200000088,
//           attrName: '产地',
//           attrId: 1200000094,
//           attrType: 1,
//           valueList: [{
//             value: 'test',
//             valueId: '',
//             valueIdPath: '',
//             valuePath: 'test',
//             selected: 1,
//             text: '',
//             sequence: 0
//           }]
//         },
//         '1200000088': {
//           id: 1200000088,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '品牌',
//           attrId: 1200000088,
//           attrType: 1,
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 0,
//           inputType: 3,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 1,
//           valueList: [{
//             value: '大苹果',
//             valueId: 123,
//             valueIdPath: '123',
//             valuePath: '大苹果',
//             selected: 1,
//             text: '',
//             sequence: 0
//           }]
//         },
//         '300005192': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: 'adfa',
//           attrId: 300005192,
//           optionMaxSize: 5,
//           attrType: 1,
//           supportExtend: true,
//           valueList: [
//             {
//               value: '1-6789',
//               valueId: 400003137,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '1-1234dsfdsfadsf5',
//               valueId: 400003136,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-xcvcxvx',
//               valueId: null,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '1-66745645',
//               valueId: 423423423423,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-666',
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '0-76765679',
//               valueId: null,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 4
//         },
//         '300005193': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '文本',
//           attrId: 300005193,
//           attrType: 1,
//           valueList: [
//             {
//               value: 'hhh',
//               selected: 1
//             }
//           ],
//           categoryId: 200000062,
//           templateId: 0,
//           isRequired: 1,
//           textMaxLength: 4096,
//           characterType: '2',
//           inputType: 3,
//           wmPoiId: '123',
//           level: 0,
//           sequence: 5
//         }
//       },
//       attrList: [],
//       picture: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg,,,,',
//       upcImage: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
//       picContent: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
//       spPicContentSwitch: 1,
//       spPicContent: "http://p0.meituan.net/scproduct/9187625ab832e8cfdb74755826ddae09280843.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/d8405b2203ada027b1ff0ad2f78a4a6a370718.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/c49ce6f332fea63cd92fef0889bad3e888259.jpg?w=1125&h=1125,http://p0.meituan.net/scproduct/9969aa40d7e6f15828dfed0b39a60bf2226215.jpg?w=2048&h=2048",
//       poorImages: [1],
//       'wmProductVideo|1': [
//         {
//           'id': 1111,
//           'length': 76,
//           title: '@name',
//           main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
//           main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
//           'size': 343,
//           url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
//           url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
//           'status|1': [1],
//           ctime: 1559216594894,
//           utime: 1559216594894,
//           'relSpuList|0-3': [
//             {
//               'id|+1': 1000,
//               name: '@name',
//               picture: 'https://avatars1.githubusercontent.com/u/9376569?s=460&v=4',
//               upcCode: '123',
//               wmProductSkus: [
//                 {
//                   upcCode: '123',
//                   price: 5,
//                   stock: 10
//                 }
//               ]
//             }
//           ],
//         },
//       ],
//       suggestedPrice: 0,
//       riseMax: 0,
//       dropMax: 0,
//       offShelfType: 0,
//       releaseType: 0,
//       upcValidFlag: 0,
//       riskMano: null,
//       labels: [{subAttr: "0", id: 1, groupId: 1, groupName: "招牌"}],
//       spuSaleAttrMap: {
//         '300000029': {
//           id: 0,
//           isLeaf: 0,
//           spuId: 0,
//           attrName: '颜色1',
//           attrId: 300000029,
//           valueList: [
//             {
//               value: '红色',
//               valueId: 0,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: null,
//               sequence: 0,
//               isCustomized: true,
//             },
//             {
//               value: '白色',
//               valueId: 1,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '黄色',
//               valueId: 2,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '绿色',
//               valueId: 3,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 0,
//           templateId: 0,
//           isRequired: 1,
//           inputType: 2,
//           attrType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 0
//         },
//         '300000030': {
//           id: 1,
//           isLeaf: 0,
//           spuId: 1,
//           attrName: '颜色2',
//           attrId: 300000030,
//           valueList: [
//             {
//               value: '红色',
//               valueId: 0,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: null,
//               sequence: 0,
//               isCustomized: true,
//             },
//             {
//               value: '白色',
//               valueId: 1,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 1,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '黄色',
//               valueId: 2,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             },
//             {
//               value: '绿色',
//               valueId: 3,
//               valueIdPath: null,
//               valuePath: null,
//               selected: 0,
//               text: '',
//               sequence: 0
//             }
//           ],
//           categoryId: 1,
//           templateId: 1,
//           isRequired: 1,
//           inputType: 2,
//           attrType: 2,
//           wmPoiId: 0,
//           level: 0,
//           sequence: 1
//         }
//       },
//       forceRelFlag: 0,
//       sellStatus: 0,
//       minOrderCount: 1,
//       shippingTimeX: '[[],["11:21-11:24"],["11:21-11:24"],[],["11:21-11:24"],[],[]]',
//       skus: [
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }],
//           minOrderCount: 1,
//           id: 130332025,
//           stock: 10,
//           price: 0,
//           upcCode: '33334444111',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 0,
//           ladderNum: 0,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332026,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '红色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '红色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332027,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         },
//         {
//           skuAttrs: [{
//             value: '白色',
//             valueId: 0,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000030,
//           }, {
//             value: '白色',
//             valueId: 1,
//             valueIdPath: null,
//             valuePath: null,
//             sequence: 0,
//             isCustomized: true,
//             attrId: 300000029,
//           }],
//           minOrderCount: 1,
//           id: 130332028,
//           stock: 20,
//           price: 0,
//           upcCode: '',
//           spec: '106ml ',
//           spuId: null,
//           bizValue: null,
//           weightUnit: '',
//           ladderPrice: 1,
//           ladderNum: 1,
//           limitStock: 1,
//           itemNum: '',
//           shelfNum: '',
//           sourceFoodCode: '',
//           weight: 106,
//           productName: null,
//           unit: '份',
//           sequence: 0
//         }
//       ],
//       title: 'Title(title:商品11, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
//       description: '',
//       items: null,
//       category: {
//         idPath: ',200000763,200000768,200000769,',
//         categoryNamePath: '中西药品,感冒用药,清热解毒',
//         isLeaf: 1,
//         categoryId: 200000769,
//         parentId: 200000087,
//         categoryName: '袋装冰激凌',
//         level: 3
//       },
//       wmPoiId: 5108726,
//       isSp: 1,
//       spId: 1
//     },
//     msg: '成功'
//   };
// };
