/**
 * @url /reuse/sc/product/shangou/r/detailProductAndMedicine
 */

module.exports = function () {
  // true 药品
  // false 商超
  return false ? {
    data: {
      releaseType: 0,
      spPicContentSwitch: 1,
      spPicContent: '',
      upcImage: null,
      description: '',
      name: '[茂祥]烧烫伤膏',
      id: 1191119590,
      labels: null,
      category: {
        lockStatus: 0,
        lockTips: null,
        level: 3,
        parentId: 200000817,
        categoryName: '烧伤烫伤',
        categoryId: 200000823,
        isLeaf: 1,
        idPath: ',200000763,200000817,200000823,',
        allowCustomProduct: true,
        categoryType: 2,
        categoryNamePath: '中西药品,皮肤用药,烧伤烫伤'
      },
      title: 'Title(title:[茂祥]烧烫伤膏, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
      wmPoiId: 2868058,
      spId: 0,
      skus: [
        {
          ladderPrice: 0,
          ladderNum: 0,
          skuAttrs: [
              {
                "setSpuId": true,
                "setAttrId": true,
                "setAttrName": true,
                "attrName": "服装颜色",
                "sequence": 1,
                "spuAttrId": 5635905209,
                "setSpuAttrId": true,
                "setValue": true,
                "valueId": 1300000169,
                "attrId": 1200004330,
                "ctime": 1607335929,
                "setId": true,
                "valid": 1,
                "wmPoiId": 8751770,
                "spuId": 2631714086,
                "utime": 1607335929,
                "skuId": 2973640001,
                "setSkuId": true,
                "setSequence": true,
                "setCtime": true,
                "setUtime": true,
                "setValid": true,
                "setValueId": true,
                "setWmPoiId": true,
                "value": "A",
                "id": 12926702
              },
              {
                "setSpuId": true,
                "setAttrId": true,
                "setAttrName": true,
                "attrName": "尺码",
                "sequence": 2,
                "spuAttrId": 5635905210,
                "setSpuAttrId": true,
                "setValue": true,
                "valueId": 1300006043,
                "attrId": 1200000095,
                "ctime": 1607335929,
                "setId": true,
                "valid": 1,
                "wmPoiId": 8751770,
                "spuId": 2631714086,
                "utime": 1607335929,
                "skuId": 2973640001,
                "setSkuId": true,
                "setSequence": true,
                "setCtime": true,
                "setUtime": true,
                "setValid": true,
                "setValueId": true,
                "setWmPoiId": true,
                "value": "M",
                "id": 12926703
              }
              ],
          oriPrice: 0,
          shippingTimeX: '-',
          minOrderCount: 1,
          skuAttrList: null,
          limitStock: 1,
          sequence: 1,
          shelfNum: '',
          itemNum: '',
          id: 1323330244,
          weight: -1,
          price: 25.8,
          weightUnit: '',
          spuId: null,
          spec: '40g',
          upcCode: '6938817511706',
          stock: 9999,
          unit: '份',
          sourceFoodCode: '',
          bizValue: null,
          productName: null,
          boxPrice: 0,
          boxNum: 0,
          enableStockEditing: false,
          relCombinationProduct: true
        },
        {
          ladderPrice: 0,
          ladderNum: 0,
          skuAttrs: [],
          oriPrice: 0,
          shippingTimeX: '-',
          minOrderCount: 1,
          skuAttrList: null,
          limitStock: 1,
          sequence: 1,
          shelfNum: '',
          itemNum: '',
          id: 1323330244,
          weight: -1,
          price: 25.8,
          weightUnit: '',
          spuId: null,
          spec: '40g',
          upcCode: '6938817511706',
          stock: 9999,
          unit: '份',
          sourceFoodCode: '',
          bizValue: null,
          productName: null,
          boxPrice: 0,
          boxNum: 0,
          enableStockEditing: false,
          relCombinationProduct: true
        },
        {
          ladderPrice: 0,
          ladderNum: 0,
          skuAttrs: [],
          oriPrice: 0,
          shippingTimeX: '-',
          minOrderCount: 1,
          skuAttrList: null,
          limitStock: 1,
          sequence: 1,
          shelfNum: '',
          itemNum: '',
          id: 1323330244,
          weight: -1,
          price: 25.8,
          weightUnit: '',
          spuId: null,
          spec: '40g',
          upcCode: '6938817511706',
          allowUpcEmpty: true,
          stock: 9999,
          unit: '份',
          sourceFoodCode: '',
          bizValue: null,
          productName: null,
          boxPrice: 0,
          boxNum: 0,
          enableStockEditing: true,
          relCombinationProduct: false
        }
      ],
      categoryAttrMap: {
        '1200000003': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 14,
          attrName: '剂型',
          id: 1952990101,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000003,
          valueList: [
            {
              sequence: 0,
              value: '软膏',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '软膏',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000004': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 15,
          attrName: '适应症',
          id: 1953036431,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000004,
          valueList: [
            {
              sequence: 0,
              value: '清热解毒，消肿止痛。用于轻度水、火烫伤。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '清热解毒，消肿止痛。用于轻度水、火烫伤。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000005': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 19,
          attrName: '注意事项',
          id: 1952990097,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000005,
          valueList: [
            {
              sequence: 0,
              value: '1.忌食辛辣刺激性食物。2.孕妇慎用。3.本品为外用药，禁止内服。4.本药使用时应注意全身情况，如有恶寒发热等症状时，应去医院就诊。5.重度、大面积烫伤时应去医院就诊。6.烧伤局部用药一定要注意创面清洁干净，在清洁环境下最好采用暴露疗法。7.轻度烧伤患者用药一至二天后症状无改善或局部有脓苔应去医院就诊。8.用药后局部出现皮疹等过敏表现者应停用。9.对本品过敏者禁用，过敏体质者慎用。10.本品性状发生改变时禁止使用。11.儿童必须在成人监护下使用。12.请将本品放在儿童不能接触的地方。13.如正在使用其他药品，使用本品前请咨询医师或药师。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '1.忌食辛辣刺激性食物。2.孕妇慎用。3.本品为外用药，禁止内服。4.本药使用时应注意全身情况，如有恶寒发热等症状时，应去医院就诊。5.重度、大面积烫伤时应去医院就诊。6.烧伤局部用药一定要注意创面清洁干净，在清洁环境下最好采用暴露疗法。7.轻度烧伤患者用药一至二天后症状无改善或局部有脓苔应去医院就诊。8.用药后局部出现皮疹等过敏表现者应停用。9.对本品过敏者禁用，过敏体质者慎用。10.本品性状发生改变时禁止使用。11.儿童必须在成人监护下使用。12.请将本品放在儿童不能接触的地方。13.如正在使用其他药品，使用本品前请咨询医师或药师。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000006': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 13,
          attrName: '性状',
          id: 1953316490,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000006,
          valueList: [
            {
              sequence: 0,
              value: '本品为淡黄的油膏，气芳香而清凉。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '本品为淡黄的油膏，气芳香而清凉。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000010': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 18,
          attrName: '禁忌',
          id: 1952990096,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000010,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000013': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 17,
          attrName: '不良反应',
          id: 1953216599,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000013,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000014': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 29,
          attrName: '贮藏',
          id: 1953316487,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000014,
          valueList: [
            {
              sequence: 0,
              value: '密闭，防潮。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '密闭，防潮。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000015': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 34,
          attrName: '温馨提示',
          id: 2629774046,
          level: 1,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 1,
          spuId: 1191119590,
          attrId: 1200000015,
          valueList: [
            {
              sequence: 0,
              value: '1.OTC药品请按药品说明书或在药师指导下购买和使用。\n2.医疗器械请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。\n3.保健品不能代替药物。\n4.由于厂家不定期的更换产品包装，如遇新包装上市可能存在更新滞后，请以收到的实货包装为准！\n5.药品属于特殊商品，除药品质量原因外，药品一经售出，不得退换。',
              text: null,
              isLeaf: 1,
              selected: 1,
              valueId: 0,
              valuePath: '1.OTC药品请按药品说明书或在药师指导下购买和使用。\n2.医疗器械请仔细阅读产品说明书或者在医务人员的指导下购买和使用，禁忌内容或者注意事项详见说明书。\n3.保健品不能代替药物。\n4.由于厂家不定期的更换产品包装，如遇新包装上市可能存在更新滞后，请以收到的实货包装为准！\n5.药品属于特殊商品，除药品质量原因外，药品一经售出，不得退换。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000016': {
          optionMaxSize: 0,
          textMaxLength: 50,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 4,
          attrName: '商品名',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000016,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000017': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 16,
          attrName: '用法用量',
          id: 1952990099,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000017,
          valueList: [
            {
              sequence: 0,
              value: '涂敷患处。',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '涂敷患处。',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000020': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 24,
          attrName: '药物相互作用',
          id: 1953036429,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000020,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000025': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 11,
          attrName: '生产厂商名称',
          id: 1953316489,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000025,
          valueList: [
            {
              sequence: 0,
              value: '通化茂祥制药有限公司',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '通化茂祥制药有限公司',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000030': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 32,
          attrName: '执行标准',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000030,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000040': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 28,
          attrName: '药代动力学',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000040,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000052': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 22,
          attrName: '老年人用药',
          id: 1953129777,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000052,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000059': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 21,
          attrName: '儿童用药',
          id: 1953036430,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000059,
          valueList: [
            {
              sequence: 0,
              value: '',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 3
        },
        '1200000061': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 25,
          attrName: '药物过量',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000061,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000080': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 31,
          attrName: '有效期',
          id: 1953216602,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000080,
          valueList: [
            {
              sequence: 0,
              value: '36个月',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '36个月',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000081': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 3,
          attrName: '是否OTC',
          id: 1952990100,
          level: 0,
          inputType: 1,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000081,
          valueList: [
            {
              sequence: 0,
              value: 'OTC',
              text: '1',
              isLeaf: 0,
              selected: 1,
              valueId: 1300000152,
              valuePath: '1',
              valueIdPath: '1300000152'
            },
            {
              sequence: 0,
              value: '非药品',
              text: '0',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000155,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '处方药',
              text: '2',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000153,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '通用品',
              text: '3',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000154,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 1
        },
        '1200000082': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 2,
          attrName: '药品通用名称',
          id: 1953129778,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000082,
          valueList: [
            {
              sequence: 0,
              value: '烧烫伤膏',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '烧烫伤膏',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 3
        },
        '1200000085': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 8,
          attrName: '产地类型',
          id: 0,
          level: 0,
          inputType: 1,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000085,
          valueList: [
            {
              sequence: 0,
              value: '国产',
              text: '1',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000003,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '进口',
              text: '2',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000004,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 164,
          isRequired: 1,
          attrType: 3
        },
        '1200000086': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 6,
          attrName: '批准文号',
          id: 1953216600,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000086,
          valueList: [
            {
              sequence: 0,
              value: '国药准字Z22024885',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '国药准字Z22024885',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 1,
          attrType: 1
        },
        '1200000088': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 5,
          attrName: '品牌名称',
          id: 1953216601,
          level: 0,
          inputType: 3,
          wmPoiId: 2868058,
          categoryId: 0,
          isLeaf: 0,
          spuId: 1191119590,
          attrId: 1200000088,
          valueList: [
            {
              sequence: 0,
              value: '茂祥',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '茂祥',
              valueIdPath: '0'
            }
          ],
          templateId: 0,
          isRequired: 2,
          attrType: 1
        },
        '1200000117': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 10,
          attrName: '是否外用',
          id: 0,
          level: 0,
          inputType: 1,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000117,
          valueList: [
            {
              sequence: 0,
              value: '是',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000096,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '否',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000095,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000150': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 26,
          attrName: '临床试验',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000150,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000151': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 33,
          attrName: '警告/警示语',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000151,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000153': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 20,
          attrName: '孕妇及哺乳期妇女',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000153,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000154': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 27,
          attrName: '药理毒理',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000154,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        },
        '1200000155': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 30,
          attrName: '包装',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000155,
          valueList: [
            {
              sequence: 0,
              value: '通化茂祥制药有限公司',
              text: null,
              isLeaf: 0,
              selected: 1,
              valueId: 0,
              valuePath: '通化茂祥制药有限公司',
              valueIdPath: '0'
            }],
          templateId: 164,
          isRequired: 1,
          attrType: 3
        },
        '1200000243': {
          optionMaxSize: 0,
          textMaxLength: 30,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '',
          application: '1,2',
          sequence: 9,
          attrName: '是否为抗生素',
          id: 0,
          level: 0,
          inputType: 1,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000243,
          valueList: [
            {
              sequence: 0,
              value: '是',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000096,
              valuePath: null,
              valueIdPath: null
            },
            {
              sequence: 0,
              value: '否',
              text: '',
              isLeaf: 0,
              selected: 0,
              valueId: 1300000095,
              valuePath: null,
              valueIdPath: null
            }
          ],
          templateId: 164,
          isRequired: 2,
          attrType: 1
        },
        '1200000311': {
          optionMaxSize: 0,
          textMaxLength: 1024,
          characterType: '1,2,3,4',
          supportFilter: 2,
          supportExtend: '1',
          application: '1,2',
          sequence: 12,
          attrName: '成份',
          id: 0,
          level: 0,
          inputType: 3,
          wmPoiId: 0,
          categoryId: 200000763,
          isLeaf: 0,
          spuId: 0,
          attrId: 1200000311,
          valueList: null,
          templateId: 164,
          isRequired: 2,
          attrType: 3
        }
      },
      spuSaleAttrMap: null,
      tagList: [
        {
          outerFtagId: -1,
          categoryCode: '',
          timeZone: '',
          sequence: 5,
          description: '',
          level: 1,
          tagName: '皮肤用药',
          extend: '',
          parentName: null,
          parentId: 0,
          topFlag: 0,
          isLeaf: 1,
          tagId: 85042890,
          appTagCode: '',
          tagType: 0,
          actPolicyId: 0,
          nodePath: '',
          buzType: 9
        }
      ],
      limitSale: '',
      sellStatus: 0,
      shippingTimeX: '-',
      picture: 'http://p0.meituan.net/xianfu/fed5b6fe6a9c434bf5ade03be64e0a90139725.jpg,http://p1.meituan.net/xianfu/65e3fffc0adfeee40301bb8dd4cd0aef89924.jpg,,,,,,',
      attrList: [],
      isSp: 0,
      poorImages: [],
      picContent: '',
      auditStatus: 0,
      wmProductVideo: null,
      suggestedPrice: 0,
      riseMax: 0,
      dropMax: 0,
      minOrderCount: 1,
      marketingPicture: 'http://p0.meituan.net/xianfu/0dab19a87b9cfcaad701f30daf0298f5215040.jpg',
      isMedicare: true,
      spVideoStatus: 0,
      spVideoVo: {
        id: 12,
        length: 200,
        title: '@name',
        main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
        main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
        url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
        url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
      },
      wmProductVideo: {
        id: 12,
        length: 100,
        title: '@name',
        main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
        main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
        url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
        url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
        'status|1': [1],
      },
      shippingTemplateId: '1001',
      shippingTemplateName: '运费模板1'
    },
    code: 0,
    msg: '成功'
  } : {
    code: 0,
    data: {
      name: '[天龙]维胺酯维E乳膏',
      id: 111111,
      saleType: 2,
      deliveryTime: 1620385000000,
      auditStatus: 0,
      limitSale: JSON.stringify({
        limitSale: false,
        begin: '20200301',
        end: '20200401',
        type: 2,
        count: 100
      }),
      tagList: [
        {
          tagName: '403二级分类',
          tagId: 96851308,
          valid: 1,
          isLeaf: 1,
          setId: true,
          setName: true,
          setSequence: true,
          setCtime: true,
          setUtime: true,
          setValid: true,
          setDescription: true,
          tagType: 0,
          parentId: 7340747,
          setWmPoiId: true,
          setPoiId: true,
          setIsLeaf: true,
          setParentName: true,
          setBuzType: true,
          appTagCode: '',
          setAppTagCode: true,
          setTopFlag: true,
          setTagType: true,
          setTimeZone: true,
          setActPolicyId: true,
          setCategoryCode: true,
          setNodePath: true,
          outerFtagId: -1,
          setOuterFtagId: true,
          setExtend: true,
          topFlag: 0,
          description: '',
          parentName: '403一级分类',
          wmPoiId: 5108726,
          setLevel: true,
          actPolicyId: 0,
          nodePath: '',
          buzType: 0,
          setParentId: true,
          categoryCode: '',
          extend: '{"sortType":2,"topCount":0}',
          utime: 1554259012,
          ctime: 1509005478,
          poiId: 0,
          timeZone: '',
          level: 2,
          sequence: 6
        }
      ],
      categoryAttrMap: {
        '300000028': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '大乳品',
          attrId: 300000028,
          attrType: 1,
          supportExtend: true,
          'valueList|3': [
            {
              value: '@name',
              'valueId|+1': [400002677, 400002678, 400002679],
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          inputType: 1,
          wmPoiId: 0,
          level: 0,
          sequence: 2
        },
        '1200000094': {
          id: 1200000088,
          attrName: '产地',
          attrId: 1200000094,
          attrType: 1,
          valueList: [{
            value: 'test',
            valueId: '',
            valueIdPath: '',
            valuePath: 'test',
            selected: 1,
            text: '',
            sequence: 0
          }]
        },
        '1200000088': {
          id: 1200000088,
          isLeaf: 0,
          spuId: 0,
          attrName: '品牌',
          attrId: 1200000088,
          attrType: 1,
          categoryId: 200000062,
          templateId: 0,
          isRequired: 0,
          inputType: 3,
          wmPoiId: 0,
          level: 0,
          sequence: 1,
          valueList: [{
            value: '大苹果',
            valueId: 123,
            valueIdPath: '123',
            valuePath: '大苹果',
            selected: 1,
            text: '',
            sequence: 0
          }]
        },
        '300005192': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: 'adfa',
          attrId: 300005192,
          optionMaxSize: 5,
          attrType: 1,
          supportExtend: true,
          valueList: [
            {
              value: '1-6789',
              valueId: 400003137,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '1-1234dsfdsfadsf5',
              valueId: 400003136,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '0-xcvcxvx',
              valueId: null,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '1-66745645',
              valueId: 423423423423,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '0-666',
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '0-76765679',
              valueId: null,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          inputType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 4
        },
        '300005193': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '文本',
          attrId: 300005193,
          attrType: 1,
          valueList: [
            {
              value: 'hhh',
              selected: 1
            }
          ],
          categoryId: 200000062,
          templateId: 0,
          isRequired: 1,
          textMaxLength: 4096,
          characterType: '2',
          inputType: 3,
          wmPoiId: '123',
          level: 0,
          sequence: 5
        }
      },
      attrList: [],
      picture: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg,,,,',
      upcImage: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
      picContent: 'http://p1.meituan.net/shangchao/3fb8bbf316164ef295ef0222c777a3a9.jpg',
      spPicContentSwitch: 1,
      spPicContent: "http://p0.meituan.net/scproduct/9187625ab832e8cfdb74755826ddae09280843.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/d8405b2203ada027b1ff0ad2f78a4a6a370718.jpg?w=1709&h=960,http://p0.meituan.net/scproduct/c49ce6f332fea63cd92fef0889bad3e888259.jpg?w=1125&h=1125,http://p0.meituan.net/scproduct/9969aa40d7e6f15828dfed0b39a60bf2226215.jpg?w=2048&h=2048",
      poorImages: [1],
      'wmProductVideo|1': [
        {
          'id': 1111,
          'length': 76,
          title: '@name',
          main_pic_small_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
          main_pic_large_url: 'http://p1.meituan.net/xianfu/133fedef1cf0b2881dd9c3d4c3c390b3231831.png',
          'size': 343,
          url_mp4: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.mp4',
          url_ogg: 'http://s3plus.meituan.net/v1/mss_959de39f2c304efda7e611d549f6b2b5/video/22F502DCF160930EE63433F43F6D9DE7.ogg',
          'status|1': [1],
          ctime: 1559216594894,
          utime: 1559216594894,
          'relSpuList|0-3': [
            {
              'id|+1': 1000,
              name: '@name',
              picture: 'https://avatars1.githubusercontent.com/u/9376569?s=460&v=4',
              upcCode: '123',
              wmProductSkus: [
                {
                  upcCode: '123',
                  price: 5,
                  stock: 10
                }
              ]
            }
          ],
        },
      ],
      suggestedPrice: 0,
      riseMax: 0,
      dropMax: 0,
      offShelfType: 0,
      releaseType: 0,
      upcValidFlag: 0,
      riskMano: null,
      labels: [{subAttr: "0", id: 1, groupId: 1, groupName: "招牌"}],
      spuSaleAttrMap: {
        '300000029': {
          id: 0,
          isLeaf: 0,
          spuId: 0,
          attrName: '颜色1',
          attrId: 300000029,
          valueList: [
            {
              value: '红色',
              valueId: 0,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: null,
              sequence: 0,
              isCustomized: true,
            },
            {
              value: '白色',
              valueId: 1,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '黄色',
              valueId: 2,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '绿色',
              valueId: 3,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 0,
          templateId: 0,
          isRequired: 1,
          inputType: 2,
          attrType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 0
        },
        '300000030': {
          id: 1,
          isLeaf: 0,
          spuId: 1,
          attrName: '颜色2',
          attrId: 300000030,
          valueList: [
            {
              value: '红色',
              valueId: 0,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: null,
              sequence: 0,
              isCustomized: true,
            },
            {
              value: '白色',
              valueId: 1,
              valueIdPath: null,
              valuePath: null,
              selected: 1,
              text: '',
              sequence: 0
            },
            {
              value: '黄色',
              valueId: 2,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            },
            {
              value: '绿色',
              valueId: 3,
              valueIdPath: null,
              valuePath: null,
              selected: 0,
              text: '',
              sequence: 0
            }
          ],
          categoryId: 1,
          templateId: 1,
          isRequired: 1,
          inputType: 2,
          attrType: 2,
          wmPoiId: 0,
          level: 0,
          sequence: 1
        }
      },
      forceRelFlag: 0,
      sellStatus: 0,
      minOrderCount: 1,
      shippingTimeX: '[[],["11:21-11:24"],["11:21-11:24"],[],["11:21-11:24"],[],[]]',
      skus: [
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }],
          minOrderCount: 1,
          id: 130332025,
          stock: 10,
          price: 0,
          upcCode: '33334444111',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 0,
          ladderNum: 0,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0,
          commonProperty: null
        },
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332026,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0,
          commonProperty: {
            allowUpcEmpty: 'true'
          }
        },
        {
          skuAttrs: [{
            value: '红色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '红色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332027,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        },
        {
          skuAttrs: [{
            value: '白色',
            valueId: 0,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000030,
          }, {
            value: '白色',
            valueId: 1,
            valueIdPath: null,
            valuePath: null,
            sequence: 0,
            isCustomized: true,
            attrId: 300000029,
          }],
          minOrderCount: 1,
          id: 130332028,
          stock: 20,
          price: 0,
          upcCode: '',
          spec: '106ml ',
          spuId: null,
          bizValue: null,
          weightUnit: '',
          ladderPrice: 1,
          ladderNum: 1,
          limitStock: 1,
          itemNum: '',
          shelfNum: '',
          sourceFoodCode: '',
          weight: 106,
          productName: null,
          unit: '份',
          sequence: 0
        }
      ],
      title: 'Title(title:商品11, manualTitle:0, rule:[TitleRule(field:originName, sort:1, weight:1), TitleRule(field:brandName, sort:2, weight:2), TitleRule(field:spName, sort:3, weight:5), TitleRule(field:flavour, sort:4, weight:4), TitleRule(field:spec, sort:5, weight:3)], h5Url:http://actreusefe.sankuai.com/h5/product/nameStitchingRule)',
      description: '',
      items: null,
      category: {
        idPath: ',200000763,200000768,200000769,',
        categoryNamePath: '中西药品,感冒用药,清热解毒',
        isLeaf: 1,
        categoryId: 200000769,
        parentId: 200000087,
        categoryName: '袋装冰激凌',
        level: 3
      },
      wmPoiId: 5108726,
      isSp: 1,
      spId: 1
    },
    msg: '成功'
  };
};
